package com.github.akruk.antlrxquery.semanticanalyzer;

public enum WarningType {
    INSTANCE_OF__ALWAYS_TRUE,
    PATH_OPERATOR__EMPTY_SEQUENCE,
    NODE_TEST__DUPLICATED_NAME,
    LOOKUP__TARGET_EMPTY,
    LOOKUP__KEY_EMPTY,
    LOOKUP__RETURNS_ALWAYS_EMPTY,
    LOOKUP__EMPTY_RECORD,
    LOOKUP__IMPOSSIBLE_RECORD_FIELD,
    IMPORT_MODULE__MANY_VALID_PATHS,
    TREAT__UNLIKELY,
    CAST__SELFCAST,
    CAST__SUBTYPE_CAST,
    CAST__TARGET_CAST,
    CAST__POSSIBLE_MANY_ITEMTYPES,
    CAST__POSSIBLE_MANY_SEQUENCETYPES,
    CASTABLE__UNNECESSARY,
    OTHERWISE__IMPOSSIBLE,


}
