package com.github.akruk.antlrxquery;

public enum XQueryAxis {
    CHILD, DESCENDANT, SELF,
    DESCENDANT_OR_SELF, FOLLOWING_SIBLING, FOLLOWING,
    PARENT, ANCESTOR, PRECEDING_SIBLING, PRECEDING,
    ANCESTOR_OR_SELF, FOLLOWING_OR_SELF, FOLLOWING_SIBLING_OR_SELF,
    PRECEDING_SIBLING_OR_SELF, PRECEDING_OR_SELF,
}
