<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
            http://maven.apache.org/POM/4.0.0
            https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>


    <parent>
        <groupId>com.github.akruk</groupId>
        <artifactId>antlrquery-parent</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>


    <artifactId>antlrquery-implementation</artifactId>


    <properties>
        <antlr4.visitor>true</antlr4.visitor>

        <junit.version>5.10.0</junit.version>
        <maven.surefire.version>3.1.2</maven.surefire.version>
    </properties>


    <dependencies>

        <dependency>
            <groupId>com.github.akruk</groupId>
            <artifactId>visitor</artifactId>
            <version>0.0.1-SNAPSHOT</version>
        </dependency>

        <dependency>
            <groupId>org.eclipse.lsp4j</groupId>
            <artifactId>org.eclipse.lsp4j</artifactId>
            <version>0.24.0</version>
        </dependency>

        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4-runtime</artifactId>
            <version>4.13.2</version>
        </dependency>

        <dependency>
            <groupId>org.antlr</groupId>
            <artifactId>antlr4</artifactId>
            <version>4.13.2</version>
        </dependency>


        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.20.0</version>
        </dependency>

        <!-- Checker annotations -->
        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker</artifactId>
            <version>3.42.0</version>
        </dependency>

        <dependency>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-qual</artifactId>
            <version>3.42.0</version>
        </dependency>
        <!-- Tests -->
        <dependency>
            <groupId>org.junit.jupiter</groupId>
            <artifactId>junit-jupiter</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mockito</groupId>
            <artifactId>mockito-core</artifactId>
            <version>5.5.0</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.27.7</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.13.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>


    <build>

        <plugins>


            <!-- ANTLR generator -->
            <plugin>
                <groupId>org.antlr</groupId>
                <artifactId>antlr4-maven-plugin</artifactId>
                <version>4.13.2</version>

                <executions>
                    <execution>
                        <goals>
                            <goal>antlr4</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>


            <!-- Java compiler + annotation processor -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.15.0</version>

                <configuration>
                    <generatedSourcesDirectory>
                        ${project.build.directory}/generated-sources/annotations
                    </generatedSourcesDirectory>

                    <release>${maven.compiler.release}</release>
                    <annotationProcessorPaths>

                        <path>
                            <groupId>com.github.akruk</groupId>
                            <artifactId>visitor-processor</artifactId>
                            <version>0.0.1-SNAPSHOT</version>
                        </path>

                        <path>
                            <groupId>com.google.auto.service</groupId>
                            <artifactId>auto-service</artifactId>
                            <version>1.1.1</version>
                        </path>

                        <path>
                            <groupId>org.checkerframework</groupId>
                            <artifactId>checker</artifactId>
                            <version>3.42.0</version>
                        </path>

                    </annotationProcessorPaths>
                </configuration>
            </plugin>


            <!-- Tests -->
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${maven.surefire.version}</version>

                <configuration>
                    <includes>
                        <include>**/*Test.java</include>
                        <include>**/*Tests.java</include>
                    </includes>
                </configuration>

            </plugin>


            <!-- Uber jars -->
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.7.1</version>

                <executions>

                    <execution>
                        <id>antlrquery-tool-jar</id>
                        <phase>package</phase>

                        <goals>
                            <goal>single</goal>
                        </goals>

                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <finalName>antlrquery-tool</finalName>

                            <archive>
                                <manifest>
                                    <mainClass>
                                        com.github.akruk.antlrquery.AntlrQueryRunner
                                    </mainClass>
                                </manifest>
                            </archive>

                            <descriptorRefs>
                                <descriptorRef>
                                    jar-with-dependencies
                                </descriptorRef>
                            </descriptorRefs>

                        </configuration>
                    </execution>


                    <execution>
                        <id>antlrquery-language-server-jar</id>
                        <phase>package</phase>

                        <goals>
                            <goal>single</goal>
                        </goals>

                        <configuration>
                            <appendAssemblyId>false</appendAssemblyId>
                            <finalName>antlrquery-language-server</finalName>

                            <archive>
                                <manifest>
                                    <mainClass>
                                        com.github.akruk.antlrquery.languageserver.AntlrQueryLanguageServer
                                    </mainClass>
                                </manifest>
                            </archive>

                            <descriptorRefs>
                                <descriptorRef>
                                    jar-with-dependencies
                                </descriptorRef>
                            </descriptorRefs>

                        </configuration>
                    </execution>

                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-antrun-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <id>copy-server-and-extension</id>
                        <phase>package</phase>
                        <configuration>
                            <target>
                                <mkdir dir="antlrqueryextension/antlrquery/server"/>
                                <copy file="${project.build.directory}/antlrquery-language-server.jar"
                                      tofile="${maven.multiModuleProjectDirectory}/antlrquery-vscode-extension/server/antlrquery-language-server.jar"
                                      overwrite="true"/>

                                <mkdir dir="${user.home}/.vscode/extensions/antlrquery"/>
                                <copy todir="${user.home}/.vscode/extensions/antlrquery" overwrite="true">
                                    <fileset dir="${maven.multiModuleProjectDirectory}/antlrquery-vscode-extension"/>
                                </copy>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>

    </build>


</project>